### ISSUE TITLE
Interne Feedback

### ISSUE THREAD

**Issue by rlegendre** [sequana/sequana#424]
Feedback from PF2:
 
- Why section is not in the same order than the config.yaml file ?
- When we copy/paste with the mouse, it's all white and we no longer see the selected line (!!)
- Display a section only if the `do` is selected?
- When we selected a design file, it must contain only fastq where we will do analyze, but we always have many projects on the same lane, and this configuration always need to modify the design file
- ( Where a config file is uploaded, it will not write in the working directory (and we cannot run sequana pipeline in command line). Same thing for `multiqc_config.ymal`)

**Comment by cokelaer** [comment]
- [x] section not in the same order as in the config file because we sort the rules. We decided to not sort the rules anymore and developers must build their config file as they wish. 
- [ ] I do not see the issue here. Maybe it was an old version used ? 
- [ ] wont fix this issue of collapsing a section if do is not selected. 
- [ ] need to be discussed further with a dedicated issue
- [x] fixed. By default the cluster_config.json found in the pipeline module (e.g. RNAseq) is loaded in the snakemake dialog. Once Save button is pressed, (1) the cluster_config.json is saved in the working directory and (2) the dialog file name is updated to point towards the working directory (so that if you press save again, the edited file in the ./working directory is not overwritten by the original file)

**Comment by cokelaer** [comment]
closing this issue. IF needed, reopen an issue
