### ISSUE TITLE
JOSS review: remove local hardcoded variables from pipeline

### ISSUE THREAD

**Issue by bow** [sequana/sequana#439]
Upon checking the pipelines, I see that `markduplicates` in the `atac-seq` and `rna-seq` pipelines still contains a hard-coded command line flag: https://github.com/sequana/sequana/blob/master/sequana/pipelines/atac-seq/config.yaml#L57 and https://github.com/sequana/sequana/blob/4943ab9dd229a9a3548975fe7be67231f60115e2/sequana/pipelines/rnaseq/config.yaml.

Could these be removed?

(Main review thread: [here](https://github.com/openjournals/joss-reviews/issues/352))

**Comment by cokelaer** [comment]
good point, we will see how to update the pipeline so that it is fully generic. thanks again for pointing this.
We are reviewing the pipelines and rules those days with more documentation so we will check this point carefully.

**Comment by cokelaer** [comment]
@bow follow up on the RNAseq and atac-seq pipelines. 

Following the tutorial and small changes, it appears that one can use the RNA-seq. There are still some hard-coded path but are not used by default. As for the atac-seq it is in the library but not yet released officially: it does not appear in the tutorial or sequanix or pipeline section in principles. We will fix the remaining hard-coded paths in the future though for the RNA-seq. I have updated the tutorial 
http://sequana.readthedocs.io/en/master/tutorial.html#rna-seq to emphasize the part that must be edited to make it working.

I suspect this would not be an issue for JOSS acceptation but if you think this is a blocking issue, please let us know, otherwise we can close this issue for now. Note, however, that I have open an independent issue to keep track of this concern in https://github.com/sequana/sequana/issues/452

**Comment by bow** [comment]
Hi @cokelaer,

If these are default values that are meant to be overwritten, I think so long as there is enough explanation in the documentation it is acceptable, but not preferred. In this case, it's more about leaking out private details of an institution's cluster to the outside world and also user experience.

However, if these values can not be overwritten and requires user to manually change it in the source directly (not via sequana), I think it's better to remove them first.

If I may go on to the technical details, can these strings not be replaced by empty strings Does sequana / sequanix understand that some config fields have values that must be given by users?

**Comment by cokelaer** [comment]
@bow sorry for the delay in solving this last issue. 

So, we slightly updated the configuration file of the rnaseq pipeline.

For now we won't remove all of the hard-coded parameters. However, these parameters have to be changed by the users anyway. Therefore they do not prevent the use of the pipelines. For example, the current default config file should be sufficient to run the pipeline locally as demonstrated in the online tutorial on the readthedocs (http://sequana.readthedocs.io/en/master/tutorial.html#rna-seq) ; I could re-run the suggested analysis, which takes about 5-10 minutes. Of course I needed to edit the configuration file as explained in the tutorial but the only section to be changed corresponds to the organism used in the example (genome section).

**Comment by bow** [comment]
@cokelaer No worries, ok then ~ so long as you're aware of this issue. It's always safest to remove any traces of local environments for these things.
