### ISSUE TITLE
sequana build

### ISSUE THREAD

**Issue by vsoch** [sequana/sequana#482]
hey @cokelaer ! This sequana image was just pushed to build, and specifically, it was the same commit, tag, and branch as a (currently) frozen build so it fired an error and is stuck in `SETUP`:

https://singularity-hub.org/collections/114

It looks like it's set up to build on commit, so my best guess is that a webhook was retriggered, or something similar? Could you walk me through the desired outcome you would want (do you want two identical containers?) and I can best debug and fix up any issues? Thanks!

**Comment by vsoch** [comment]
Specifically, it's an integrity error for the database - I set a restriction on container tag, name, commit, branch, and collection being unique.

```
IntegrityError: duplicate key value violates unique constraint "main_container_name_tag_collection_id_b_3b159866_uniq"
DETAIL:  Key (name, tag, collection_id, branch, commit)=(sequana/sequana, latest, 114, release_0_6_0, 13b415a3b33991b93a0f9e15d8a15b1ab2603a32) already exists.

```

**Comment by cokelaer** [comment]
@vsoch Thanks for the feedback about the "status setup". I probably commited the same file instead of the second Singularity file. 

I'm still wondering what would be the best strategy at the moment to share the containers. 

At the moment, I created 2 singularity files in ./singularity of my project. In the master branch (selected in singularity-hub website), I committed the 2 singularity files (named Singularity and singularity_0_6_0 for release 0.6.0) and the built were succesful. I therefore froze the two containers. 

Then, I thought that I should have a specific 0.6.0 release branch in github. Like a snapshot of the project. 
I therefore commited again 2 singularity (the same). But this was a bit naive. 

I will simplify this strategy to a single Singularity file but different branches.

**Comment by vsoch** [comment]
@cokelaer thanks for the details! This is more of a personal preference, but I usually attribute releases with "tagged releases" in Github..and it looks like you've found this as well, haha:

![image](https://user-images.githubusercontent.com/814322/31938511-a0b25f44-b86c-11e7-9152-a401509ce1e6.png)

Branches are useful (imho) if you want to better control building vs. testing. I like to have a development branch that I merge into master (and then it builds) only when I'm ready.
