### ISSUE TITLE
atropos must be 1.1.16?

### ISSUE THREAD

**Issue by huangl07** [sequana/sequana#573]
When I was install sequana ,it turns out you must use atropos1.1.16,but I install 1.1.16 have some error ?

new version atropos is ok,how could it be ?

**Comment by cokelaer** [comment]
Indeed, in the master version of sequana, we currently pinned atropos to 1.1.16. So, if you install sequana in a new environement, the version 1.1.16 will be installed. If later, you install a new version of atropos, since sequana is already installed, there is no more check on atropos version as far as I know. Using a new version of atropos should not be a problem. We specify atropos to be 1.1.16 because we built the test with that specific version. In fact we should rather us atropos>=1.1.16 rather than exact version 1.1.16. We will change that behaviour in the next release. thanks for reporting this behaviour.
