### ISSUE TITLE
Paired-end data

### ISSUE THREAD

**Issue by benoistlaurent** [sequana/sequana#612]
# Please fill those information if known:

```
$ sequana_rnaseq --version
Sequana version used: 0.11.1
Sequana_pipetools version used: 0.5.2
pipeline sequana_rnaseq version used: 0.13.0
```

# Description of your problem with error message 

Hi,

I have paired-end data to analyse but realized I don't know what's the proper way to deal with this data in `sequana`.
Should I change something or `sequana` will automatically "guess" that data is paired-end?

Thanks in advance.

**Comment by ddesvillechabrol** [comment]
Hello !

Sequana will guess if you set the correct `input_readtag` in the `config.yaml` file.
For example, if I have those files in a data folder:

```
sample1_R1_.fq.gz
sample1_R2_.fq.gz
sample2_R1_.fq.gz
sample2_R2_.fq.gz
```

In your config file you'll need those options:
```yaml
input_directory: data
input_readtag: _R[12]_
input_pattern: *fq.gz
```

Cheers,
Dimitri

**Comment by cokelaer** [comment]
@benoistlaurent indeed sequana will guess the type of data based on the readtag. 
Another standard naming convention is to set the read tag as numbers 1 and 2 before fastq.gz extension. Let us consider here the single end case

```
sample1_1.fastq.gz
sample2_1.fastq.gz
```

Then, in your config file you'll need those options:
```yaml
input_directory: data
input_readtag: _[12].
input_pattern: *fastq.gz
```
because there is no paired data found for the tag 1, Sequana guesses that it is single-ended.

For most of the sequencing data we dealwith the _R1_ and _R2_ tag are used and if you extension is fastq.gz there is nothing to change in fact.
